- hosts: localhost
  vars:
    ssh_dest: "{{ lookup('env', 'HOME') }}/.ssh/"
  vars_files:
    - ./vault.yml
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/productivity-tools.yml
