- name: Add neovim apt repo
  apt_repository: 
    repo: ppa:neovim-ppa/unstable
    state: present
  tags:
    - install
    - neovim

- name: Install neovim 
  apt:
    update_cache: yes
    name: neovim
    state: present
  tags:
    - install
    - neovim

