- name: Ensure .ssh directory exists.
  file:
    dest: ~/.ssh/
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key
  template:
    src: templates/id_rsa.j2
    dest: ~/.ssh/id_rsa
    mode: 0600
    decrypt: true
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh key public
  template:
    src: templates/id_rsa.pub.j2
    dest: ~/.ssh/id_rsa.pub
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key took from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    state: present
    key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
